name: Docker Image CI

on:
  workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nekopack-helper:fitpack
  
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Push the Docker image
      run: docker image push ashdroid4/nekopack-helper:fitpack
